/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import static org.junit.Assert.*;

import org.junit.Assert;

import auctiontelegram.App;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        //Library classUnderTest = new Library();
    	try {
        	App.main(new String[]{ null });
    	} catch (Exception e) {
  
    	}  		
    }
}
